name: Docker CI

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Generate short SHA
      - name: Extract metadata
        id: meta
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # ✅ LINTING PART
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      # Docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      # Build & Push
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/node-hello:latest
            ${{ secrets.DOCKER_USERNAME }}/node-hello:${{ steps.meta.outputs.SHORT_SHA }}

      # Update ArgoCD repo
      - name: Update ArgoCD repo with new image tag
        run: |
          SHORT_SHA=${{ steps.meta.outputs.SHORT_SHA }}

          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git clone https://x-access-token:${{ secrets.ARGOCD_REPO_TOKEN }}@github.com/M-Samii/node-hello-argocd.git
          cd node-hello-argocd

          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/node-hello:${SHORT_SHA}|g" k8s/deployment.yaml

          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${SHORT_SHA}" || echo "No changes"
          git push